const tarotDeck = [
    // Major Arcana
    { name: "The Fool", image: "🃏", meaning: "New beginnings, innocence, spontaneity, free spirit" },
    { name: "The Magician", image: "🎩", meaning: "Manifestation, resourcefulness, power, inspired action" },
    { name: "The High Priestess", image: "👸", meaning: "Intuition, sacred knowledge, divine feminine, subconscious mind" },
    { name: "The Empress", image: "👑", meaning: "Femininity, beauty, nature, nurturing, abundance" },
    { name: "The Emperor", image: "🤴", meaning: "Authority, establishment, structure, father figure" },
    { name: "The Hierophant", image: "⛪", meaning: "Spiritual wisdom, religious beliefs, conformity, tradition" },
    { name: "The Lovers", image: "💕", meaning: "Love, harmony, relationships, values alignment" },
    { name: "The Chariot", image: "🏇", meaning: "Control, willpower, success, determination" },
    { name: "Strength", image: "🦁", meaning: "Strength, courage, persuasion, influence, compassion" },
    { name: "The Hermit", image: "🕯️", meaning: "Soul searching, introspection, inner guidance" },
    { name: "Wheel of Fortune", image: "🎡", meaning: "Good luck, karma, life cycles, destiny, turning point" },
    { name: "Justice", image: "⚖️", meaning: "Justice, fairness, truth, cause and effect, law" },
    { name: "The Hanged Man", image: "🙃", meaning: "Suspension, restriction, letting go, sacrifice" },
    { name: "Death", image: "💀", meaning: "Endings, beginnings, change, transformation, transition" },
    { name: "Temperance", image: "🧘", meaning: "Balance, moderation, patience, purpose" },
    { name: "The Devil", image: "😈", meaning: "Shadow self, attachment, addiction, restriction, sexuality" },
    { name: "The Tower", image: "🗼", meaning: "Sudden change, upheaval, chaos, revelation, awakening" },
    { name: "The Star", image: "⭐", meaning: "Hope, faith, purpose, renewal, spirituality" },
    { name: "The Moon", image: "🌙", meaning: "Illusion, fear, anxiety, subconscious, intuition" },
    { name: "The Sun", image: "☀️", meaning: "Positivity, fun, warmth, success, vitality" },
    { name: "Judgement", image: "📯", meaning: "Judgement, rebirth, inner calling, absolution" },
    { name: "The World", image: "🌍", meaning: "Completion, accomplishment, travel, fulfillment" },

    // Cups (Hearts/Emotions)
    { name: "Ace of Cups", image: "🏆", meaning: "Love, new relationships, compassion, creativity" },
    { name: "Two of Cups", image: "💑", meaning: "Unified love, partnership, mutual attraction" },
    { name: "Three of Cups", image: "🥂", meaning: "Celebration, friendship, creativity, community" },
    { name: "Four of Cups", image: "😔", meaning: "Meditation, contemplation, apathy, reevaluation" },
    { name: "Five of Cups", image: "😢", meaning: "Regret, failure, disappointment, pessimism" },
    { name: "Six of Cups", image: "🎁", meaning: "Revisiting the past, childhood memories, innocence" },
    { name: "Seven of Cups", image: "☁️", meaning: "Opportunities, choices, wishful thinking, illusion" },
    { name: "Eight of Cups", image: "🚶", meaning: "Disappointment, abandonment, withdrawal, escapism" },
    { name: "Nine of Cups", image: "😊", meaning: "Contentment, satisfaction, gratitude, wish fulfillment" },
    { name: "Ten of Cups", image: "🏠", meaning: "Divine love, blissful relationships, harmony, alignment" },
    { name: "Page of Cups", image: "📜", meaning: "Creative opportunities, intuitive messages, curiosity" },
    { name: "Knight of Cups", image: "🐎", meaning: "Creativity, romance, charm, imagination" },
    { name: "Queen of Cups", image: "👸", meaning: "Compassionate, caring, emotionally stable, intuitive" },
    { name: "King of Cups", image: "🤴", meaning: "Emotionally balanced, compassionate, diplomatic" },

    // Wands (Fire/Passion)
    { name: "Ace of Wands", image: "🔥", meaning: "Inspiration, new opportunities, growth" },
    { name: "Two of Wands", image: "🗺️", meaning: "Future planning, making decisions, leaving comfort zone" },
    { name: "Three of Wands", image: "⛵", meaning: "Expansion, foresight, overseas opportunities" },
    { name: "Four of Wands", image: "🎉", meaning: "Celebration, joy, harmony, relaxation, homecoming" },
    { name: "Five of Wands", image: "⚔️", meaning: "Conflict, disagreements, competition, tension" },
    { name: "Six of Wands", image: "🏆", meaning: "Success, public recognition, progress, self-confidence" },
    { name: "Seven of Wands", image: "🛡️", meaning: "Challenge, competition, protection, perseverance" },
    { name: "Eight of Wands", image: "💨", meaning: "Movement, fast paced change, action, alignment" },
    { name: "Nine of Wands", image: "🏰", meaning: "Resilience, courage, persistence, test of faith" },
    { name: "Ten of Wands", image: "🎒", meaning: "Burden, extra responsibility, hard work, completion" },
    { name: "Page of Wands", image: "📋", meaning: "Inspiration, ideas, discovery, limitless potential" },
    { name: "Knight of Wands", image: "🐴", meaning: "Energy, passion, inspired action, adventure" },
    { name: "Queen of Wands", image: "👑", meaning: "Courage, confidence, independence, social butterfly" },
    { name: "King of Wands", image: "🦁", meaning: "Natural leader, vision, entrepreneur, honour" },

    // Swords (Air/Mind)
    { name: "Ace of Swords", image: "⚔️", meaning: "Breakthrough, clarity, sharp mind" },
    { name: "Two of Swords", image: "🤔", meaning: "Difficult decisions, weighing options, indecision" },
    { name: "Three of Swords", image: "💔", meaning: "Heartbreak, emotional pain, sorrow, grief" },
    { name: "Four of Swords", image: "😴", meaning: "Rest, relaxation, meditation, contemplation" },
    { name: "Five of Swords", image: "😤", meaning: "Conflict, disagreements, competition, defeat" },
    { name: "Six of Swords", image: "⛵", meaning: "Transition, change, rite of passage, releasing baggage" },
    { name: "Seven of Swords", image: "🥷", meaning: "Betrayal, deception, getting away with something" },
    { name: "Eight of Swords", image: "🪢", meaning: "Negative thoughts, self-imposed restriction, imprisonment" },
    { name: "Nine of Swords", image: "😰", meaning: "Anxiety, worry, fear, depression, nightmares" },
    { name: "Ten of Swords", image: "🗡️", meaning: "Painful endings, deep wounds, betrayal, loss" },
    { name: "Page of Swords", image: "📖", meaning: "New ideas, curiosity, thirst for knowledge" },
    { name: "Knight of Swords", image: "🏇", meaning: "Ambitious, action-oriented, driven to succeed" },
    { name: "Queen of Swords", image: "👸", meaning: "Independent, unbiased judgement, clear boundaries" },
    { name: "King of Swords", image: "🤴", meaning: "Mental clarity, intellectual power, authority" },

    // Pentacles (Earth/Material)
    { name: "Ace of Pentacles", image: "💰", meaning: "A new financial or career opportunity, manifestation" },
    { name: "Two of Pentacles", image: "⚖️", meaning: "Multiple priorities, time management, prioritisation" },
    { name: "Three of Pentacles", image: "🏗️", meaning: "Collaboration, learning, implementation" },
    { name: "Four of Pentacles", image: "🏦", meaning: "Saving money, security, conservatism, scarcity" },
    { name: "Five of Pentacles", image: "🥶", meaning: "Financial loss, poverty, lack mindset, isolation" },
    { name: "Six of Pentacles", image: "🤝", meaning: "Giving, receiving, sharing wealth, generosity" },
    { name: "Seven of Pentacles", image: "🌱", meaning: "Long-term view, sustainable results, perseverance" },
    { name: "Eight of Pentacles", image: "🔨", meaning: "Apprenticeship, repetitive tasks, mastery, skill development" },
    { name: "Nine of Pentacles", image: "🏡", meaning: "Abundance, luxury, self-reliance, financial independence" },
    { name: "Ten of Pentacles", image: "👨‍👩‍👧‍👦", meaning: "Wealth, financial security, family, long-term success" },
    { name: "Page of Pentacles", image: "📚", meaning: "Learning, studying, new ideas, financial opportunity" },
    { name: "Knight of Pentacles", image: "🐢", meaning: "Hard work, productivity, routine, conservatism" },
    { name: "Queen of Pentacles", image: "🌿", meaning: "Nurturing, practical, providing financially, down-to-earth" },
    { name: "King of Pentacles", image: "💎", meaning: "Financial success, business acumen, security, discipline" }
];

const psychicResponses = [
    "The cards whisper secrets of your destiny...",
    "I sense powerful energies surrounding your question...",
    "The universe has chosen these cards for you...",
    "Ancient wisdom flows through these sacred symbols...",
    "Your spiritual guides have spoken through the cards...",
    "The cosmic forces align to reveal your path...",
    "These cards hold the keys to your inner truth...",
    "The mystical energies have drawn these cards to you..."
];